### PR TITLE
[WIP] Devise Integration

### PR DESCRIPTION
**Pull request by jimbeaudoin**
This is a work in progress. Please do not merge.

Thanks,

### CODE REVIEW

**Comment by abhayathapa** [comment]
@jimbeaudoin devise with facebook integration would be really helpful. And please do brief something about backend in rails

**Comment by jimbeaudoin** [comment]
@marcoow I think it is going to be best if we create a new branch called devise for this. Because with the mock server and the rails backend, we have a conflict when sending data. The "server" folder must be removed or renamed to resolve the issue.

Otherwise, I can make something like this.
http://discuss.emberjs.com/t/how-to-disable-http-mock-server-within-environment-config-file/6660/5

Thanks,

**Comment by marcoow** [comment]
The Rails server shouldn't be in this repo. Either uses an Ember CLI mock server or create a separate repo for the Rails server.

**Comment by jimbeaudoin** [comment]
Ok but the whole point of this PR was to show how to work with the devise rails server and ember-simple-auth. https://github.com/simplabs/ember-simple-auth/issues/720#issuecomment-150130657 is what give me the ok to do this.

Anyway, I'm going to do it in another repos.

Thanks,

**Comment by abhayathapa** [comment]
@jimbeaudoin its a good idea to create separate repo for rails server having devise and just address devise and fb with this repo

**Comment by jimbeaudoin** [comment]
@abhayathapa You can take a look at this repos for an example with devise.

https://github.com/jimbeaudoin/ember-simple-auth-devise-example

**Pull request closed without merging**
